project:
  type: website

website:
  title: "chechoid.netlify.app"
  site-url: "https://chechoid.netlify.app"
  description: "Un blog sobre R y People Analytics"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chechoid
      - icon: twitter
        href: https://twitter.com/sergiogarciamor
      - icon: linkedin
        href: https://linkedin.com/in/sergiogarciamora
format:
  html:
    theme:
      light: minty
      dark: slate
    css: styles.css
    highlight-style: nord

editor: visual

