project:
  type: website

website:
  title: "chechoid.netlify.app"
  site-url: "https://chechoid.netlify.app"
  description: "Un blog sobre People Analytics, R y Python"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chechoid
      - text: "{{<fa brands bluesky>}}"
        href: https://bsky.app/profile/checho-puchero.bsky.social
      - icon: linkedin
        href: https://linkedin.com/in/sergiogarciamora
      - text: "Idioma / Language"
        menu:
        - text: Español
          href: /es/
        - text: English
          href: /en/
          
format:
  html:
    theme:
      light: yeti
      dark: slate
    css: styles.css
    highlight-style: nord

babelquarto:
  languagecodes:
  - name: en
    text: "English"
  - name: es
    text: "Español"
  mainlanguage: 'es'
  languages: ['en']
title-en: "chechoid.netlify.app"
description-en: My blog of People Analytics, R & Python
author-en: Sergio Garcia Mora aka Checho
lang: es
